#!/usr/bin/env node

/**
 * CLI for Ky OpenAPI Generator
 */

import * as fs from 'fs';
import * as path from 'path';
import { parseArgs as parseArgsUtil } from 'node:util';
import { OpenAPIParser } from './parser';
import { KyClientGenerator } from './generator';
import { OpenAPISpec } from './types';

interface CLIOptions {
  output?: string;
  baseUrl?: string;
  clientName?: string;
  typesOnly?: boolean;
  banner?: string;
  checksum?: string;
}

function parseArgs(): { specPath: string; options: CLIOptions } {
  const { values, positionals } = parseArgsUtil({
    args: process.argv.slice(2),
    options: {
      output: {
        type: 'string',
        short: 'o',
        description: 'Output file path (default: stdout)',
      },
      baseUrl: {
        type: 'string',
        short: 'b',
        description: 'Base URL for API (overrides spec URL)',
      },
      clientName: {
        type: 'string',
        short: 'c',
        description: 'Name of generated client class (default: ApiClient)',
      },
      banner: {
        type: 'string',
        description: 'Banner comment to prepend to generated file',
      },
      checksum: {
        type: 'string',
        description: 'Include checksum of input file in output (crc32, md5, sha1, sha256, default: md5)',
      },
      typesOnly: {
        type: 'boolean',
        short: 't',
        description: 'Generate only TypeScript types (no client class)',
      },
      help: {
        type: 'boolean',
        short: 'h',
        description: 'Show this help message',
      },
      version: {
        type: 'boolean',
        short: 'v',
        description: 'Show version',
      },
    },
    strict: true,
    allowPositionals: true,
  });

  if (values.help) {
    printHelp();
    process.exit(0);
  }

  if (values.version) {
    printVersion();
    process.exit(0);
  }

  if (positionals.length === 0) {
    printHelp();
    process.exit(1);
  }

  const specPath = positionals[0];
  const options: CLIOptions = {
    output: values.output,
    baseUrl: values.baseUrl,
    clientName: values.clientName,
    banner: values.banner,
    checksum: values.checksum,
    typesOnly: values.typesOnly,
  };

  return { specPath, options };
}

function printHelp(): void {
  console.log(`
Ky OpenAPI Generator - Generate typed HTTP clients from OpenAPI specs

Usage:
  ky-openapi-gen <spec-path> [options]

Arguments:
  <spec-path>    Path to OpenAPI specification file (JSON or YAML)

Options:
  -o, --output       Output file path (default: stdout)
  -b, --baseUrl      Base URL for API (overrides spec URL)
  -c, --clientName   Name of generated client class (default: ApiClient)
  --banner           Banner comment to prepend to generated file
  --checksum         Include checksum of input file (crc32, md5, sha1, sha256, default: md5)
  -t, --typesOnly    Generate only TypeScript types (no client class)
  -h, --help         Show this help message
  -v, --version      Show version

Examples:
  # Generate client to stdout
  ky-openapi-gen openapi.json

  # Generate client to file
  ky-openapi-gen openapi.json --output client.ts

  # Custom base URL and client name
  ky-openapi-gen openapi.json -b https://api.example.com -c MyApiClient

  # Add a banner to the generated file
  ky-openapi-gen openapi.json --banner "Auto-generated by ky-openapi-generator"

  # Include checksum of input file (using SHA256)
  ky-openapi-gen openapi.json --checksum sha256 --output client.ts

  # Generate types only
  ky-openapi-gen openapi.json --typesOnly
`);
}

function printVersion(): void {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const pkg = require('../package.json');
  console.log(`Ky OpenAPI Generator v${pkg.version}`);
}

function loadSpec(specPath: string): OpenAPISpec {
  if (!fs.existsSync(specPath)) {
    console.error(`Error: Specification file not found: ${specPath}`);
    process.exit(1);
  }

  try {
    const content = fs.readFileSync(specPath, 'utf-8');

    // Try to parse as JSON
    try {
      return JSON.parse(content);
    } catch {
      // If JSON parsing fails, provide helpful error
      console.error(`Error: Failed to parse specification file. Make sure it's valid JSON.`);
      process.exit(1);
    }
  } catch (error) {
    console.error(`Error reading specification file: ${error}`);
    process.exit(1);
  }
}

async function main(): Promise<void> {
  try {
    const { specPath, options } = parseArgs();

    console.error(`Loading specification from: ${specPath}`);
    const spec = loadSpec(specPath);

    console.error(`Parsing OpenAPI specification...`);
    const parser = new OpenAPIParser(spec);
    const endpoints = parser.parse();
    console.error(`Found ${endpoints.length} endpoints`);

    const baseUrl = options.baseUrl || parser.getBaseUrl();
    const clientName = options.clientName || 'ApiClient';
    const checksumMethod = (options.checksum as 'crc32' | 'md5' | 'sha1' | 'sha256') || 'md5';

    console.error(`Generating Ky HTTP client...`);
    const generator = new KyClientGenerator(endpoints, {
      baseUrl,
      clientName,
      typesOnly: options.typesOnly,
      banner: options.banner,
      checksumMethod: options.checksum ? checksumMethod : undefined,
      inputFilePath: options.checksum ? specPath : undefined,
    });

    const code = generator.generate();

    if (options.output) {
      const outputDir = path.dirname(options.output);

      // Create output directory if it doesn't exist
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      fs.writeFileSync(options.output, code);
      console.error(`✓ Client generated successfully: ${options.output}`);
    } else {
      console.log(code);
    }
  } catch (error) {
    console.error(`Error: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}

main();
